# configuration for mujoco_rl_him
policy_path: "pre_train/pineapplev0/policy_Aug29_16-51-02_.pt"
# policy_path: "pre_train/pineapplev0/policy_1.pt"
xml_path: "robots/biped/xml/quick_scence.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [20, 20, 0, 20, 20, 0]
kds: [0.5, 0.5, 0.3, 0.5, 0.5, 0.3]
# kps: [20, 20, 0, 20, 20, 0]
# kds: [0.5, 0.5, 1.0, 0.5, 0.5, 1.0]


# default_angles: [1.22, -1.92, 0, 1.22, -1.92, 0]
default_angles: [1.401, -2.0717, 0, 1.401, -2.0717, 0]
# default_angles: [0.9219, -1.4399, 0, 0.9219, -1.4399, 0]

lin_vel_scale: 2.0
ang_vel_scale: 0.25

dof_pos_scale: 1.0
dof_vel_scale: 0.05
pos_action_scale: 0.5  # 0.5
vel_action_scale: 5.0
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 6
num_obs: 150
one_step_obs_size: 25
obs_buffer_size: 6
leg_joint_indices: [0, 1, 3, 4]
wheel_joint_indices: [2, 5]

cmd_init: [0.0, 0.0, 0.0]
